kivy/plyer

plyer/platforms/linux/uniqueid.py

use environ to change LANG to 'C' while calling lshw

---

plyer/utils.py

https://github.com/kivy/plyer/issues/109

responds to issue 109 https://github.com/kivy/plyer/issues/109

---

README.rst

Hi,
Tested on my phone with API = 9 (android 2.3).  
More about that issue: https://github.com/kivy/plyer/issues/42

update info about support email for android<4.0

---

plyer/platforms/linux/email.py

Hi,
Its related to that issue: https://github.com/kivy/plyer/issues/131

linux email import fix

---

plyer/platforms/android/gps.py

Accuracy of location fix is quiet important in many applications, I certainly can't do without, probably others would like to use it as well.

Added accuracy argument to on_location call.

---

examples/call/buildozer.spec
examples/call/main.py
plyer/__init__.py
plyer/facades/__init__.py
plyer/facades/call.py
plyer/platforms/android/call.py

User can make calls via the application or via the phone.

Dial or Call for android

---

plyer/platforms/android/__init__.py

Using try/except doesn't work with autoclass, as it ends up raising a JVM exception related to the original class not found exception.

check android for namespace, otherwise use renpy

---

plyer/platforms/linux/battery.py

UPower daemon  does not have a option called power supply instead in "state"  it shows the state weather its charging or not.

Fixed issue #221

---

examples/gps/main.py
plyer/facades/gps.py
plyer/platforms/android/gps.py

Adding 2 parameters to make the defaults (minTime and minDistance) configurable by the user.

Make gps request parameters configurable

---

examples/flash/buildozer.spec
examples/flash/main.py
plyer/facades/flash.py

Add flash example.
Note: This is tested and could be merged. :)

Add flash example

---

plyer/platforms/ios/gps.py

fix gps issue for ios

---

plyer/facades/accelerometer.py
plyer/facades/audio.py
plyer/facades/battery.py
plyer/facades/call.py
plyer/facades/camera.py
plyer/facades/compass.py
plyer/facades/email.py
plyer/facades/filechooser.py
plyer/facades/flash.py
plyer/facades/gps.py
plyer/facades/gyroscope.py
plyer/facades/irblaster.py
plyer/facades/notification.py
plyer/facades/orientation.py
plyer/facades/sms.py
plyer/facades/tts.py
plyer/facades/uniqueid.py
plyer/facades/vibrator.py
plyer/facades/wifi.py

Adding small examples for each facade.
It's easier for new users to see these small examples and test them to get a feel of how to work with plyer.
Ready to be merged.

Adding small examples in facade files

---

plyer/platforms/macosx/notification.py

I rewrite the notification feature on mac using PyOBJus. 
I have tested it on my MacBook, and it works fine.
The original code is written two years ago, and it seems it doesn't work. Besides, it uses  PyObjC instead of PyOBJus.

Rewrite notification on Mac using PyOBJus

---

examples/accelerometer/basic/main.py
examples/accelerometer/using_graph/main.py
examples/battery/main.py
examples/call/main.py
examples/compass/main.py
examples/flash/main.py
examples/notification/main.py
examples/sms/main.py
examples/text2speech/main.py
examples/wifi/main.py

Some of the example apps does not contain `on_pause` function due to which, when the app is relaunched after pressing the home button, app restarts. Adding the `on_pause` function will cause the app to start from state where it was before leaving.

Add on_pause function

---

README.rst
examples/barometer/buildozer.spec
examples/barometer/main.py
plyer/__init__.py
plyer/facades/__init__.py
plyer/facades/barometer.py
plyer/platforms/android/barometer.py

Barometer api for android platform.
This pr is based on #160 and no additional changes were required except for rebasing since the original pr branch is 117 commits behind master branch.
Tested on:
Device - Samsung Galaxy S6 Edge
Toolchain - old and new both
Android api - 19
Android sdk - 24

Plyer android pressure sensor

---

plyer/facades/light.py
plyer/facades/temperature.py

Add version tags in light and temperature facade

---

README.rst

Supported APIs table got messed up so fixed it.

Modify readme

---

examples/uniqueid/buildozer.spec
examples/uniqueid/main.py
plyer/facades/uniqueid.py

Tested on:
**Android**
Device - Samsung Galaxy S6 Edge
Android api - 19
Android sdk - 24
Android ndk - r9c
**Linux**
OS - Ubuntu 16.04 LTS

Example for Unique ID facade

---

plyer/platforms/win/libs/balloontip.py

I really thought I pushed the change already O_o
anyway, closes #318

Fix notification ticker error + pep8

---

README.rst
examples/spatialorientation/buildozer.spec
examples/spatialorientation/main.py
plyer/__init__.py
plyer/facades/__init__.py
plyer/facades/spatialorientation.py
plyer/platforms/android/spatialorientation.py

Spatial orientation sensor api for android platform.
Computes the device's orientation based on the rotation matrix.
Tested and working fine. Can be merged

Spatial Orientation for android

---

README.rst
examples/brightness/buildozer.spec
examples/brightness/main.py
plyer/__init__.py
plyer/facades/__init__.py
plyer/facades/brightness.py
plyer/platforms/android/brightness.py
plyer/platforms/ios/brightness.py

Tested and working fine.
**Tested on**
**Device** - Xiaomi Redmi Note 4
**Android API** - 19
**Android SDK** - 20
**Android NDK** - 9c

Brightness API

---

plyer/platforms/ios/gyroscope.py

Fix iOS Gyroscope crash issue

---

examples/gyroscope/buildozer.spec
examples/gyroscope/main.py
plyer/facades/gyroscope.py
plyer/platforms/android/gyroscope.py
plyer/platforms/ios/gyroscope.py

Methods for accessing gyroscope uncalibrated sensor are added in current gyroscope API.
Example for gyroscope api is also created.
Tested and working fine. Can be merged.

Gyroscope uncalibrated sensor

---

README.rst
examples/brightness/main.py
plyer/platforms/linux/brightness.py

Brightness feature for Linux platform

Linux Brightness API

---

plyer/platforms/linux/orientation.py

Orientation feature for linux. It has been implemented with the help of xrandr.
Pr is in working condition and ready to be merged.

orientation feature for linux

---

plyer/platforms/linux/battery.py

If output object can be decoded once.

why should decode 'l' again and again

---

README.rst

"Notifications" appears twice.

Updates README.rst, removes dup in supported API

---

plyer/platforms/linux/brightness.py
plyer/platforms/linux/notification.py

- brightness.py: don't assume a Debian based system
- notification.py:
- replace bad advice to use sudo + pip
- elaborate on the package name

Improve messages for missing dependencies

---

plyer/platforms/linux/battery.py
plyer/tests/test_battery.py

Should give us a very stable point for this api on gnu/linux. Haven't checked the exact kernel version, I'll update it in the future.

Add linux battery from sysclass

---

plyer/platforms/android/bluetooth.py
plyer/platforms/macosx/bluetooth.py
plyer/platforms/macosx/notification.py

Fixes detected pep8 issues and visible style issues.

Fix pep8 issues in files

---

appveyor.yml
entrypoint.sh

errors will be fixed incrementally in the future

Disable all Pylint errors to fix red jobs

---

README.rst

Mark new audio recording feature in README.rst

---

README.rst
examples/screenshot/main.py
plyer/__init__.py
plyer/facades/__init__.py
plyer/facades/screenshot.py
plyer/facades/wifi.py
plyer/platforms/macosx/screenshot.py

OSX Screenshot (Rebased PR #324)

---

plyer/facades/wifi.py
plyer/platforms/linux/wifi.py
plyer/platforms/macosx/wifi.py

Rebased #236.
Enable and disable methods work fine on Linux Mint.

Add enable & disable WiFi for Linux and MacOS

---

plyer/platforms/macosx/bluetooth.py

Removed unnecessary grep dependency from macOS bluetooth implementation, using python instead.

Removed unnecessary grep dependency

---

plyer/platforms/linux/wifi.py

ref #477, fixes linter warning about that.

Move TODO item to a separate issue

---

.gitignore
plyer/tests/test_audio.py
plyer/tests/test_battery.py
plyer/tests/test_bluetooth.py
plyer/tests/test_storagepath.py

This pull request includes 6 new tests for macOS features:
1. audio.py
2. battery.py
3. bluetooth.py
4. storagepath.py

macOS tests - audio, battery, bluetooth, storagepath

---

plyer/platforms/android/notification.py

https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels
Using whole package name as the unique id for notification channel, the rest (such as channel name) is optional since Android cares only about the id. According to the Android docs re-creating the channel does nothing if the values are preserved.
> Creating an existing notification channel with its original values performs no operation, so it's safe to call this code when starting an app.

Fix android notifications missing channel on Oreo and later

---

plyer/platforms/ios/gps.py

Fix has been known for some years to address #240, but a pull request hadn't been created yet.

Addresses plyer issue #240.

---

plyer/platforms/android/filechooser.py

Prevent re-binding of callback on each call

---

examples/accelerometer/basic/main.py
examples/accelerometer/using_graph/main.py
examples/battery/main.py
examples/brightness/main.py
examples/camera/basic/main.py
examples/flash/main.py
examples/notification/main.py
examples/speech2text/main.py
examples/storagepath/main.py
examples/text2speech/main.py
plyer/facades/__init__.py
plyer/platforms/ios/flash.py
plyer/platforms/linux/keystore.py
plyer/platforms/linux/notification.py
plyer/platforms/linux/tts.py
plyer/platforms/linux/wifi.py
plyer/platforms/macosx/keystore.py
plyer/platforms/macosx/libs/osx_motion_sensor.py
plyer/platforms/macosx/notification.py
plyer/platforms/win/filechooser.py
plyer/platforms/win/keystore.py
plyer/platforms/win/libs/wifi_defs.py
plyer/utils.py

This does not include the py2 warnings as py2 support is being dropped in this plyer version.

Fix linter warnings

---

plyer/platforms/win/battery.py

Modification to adapt that the source of information is a flag that includes multiple conditions. See.
https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-system_power_status
Associated to issue #541

Modification of Status isCharging in windows

---

plyer/platforms/macosx/filechooser.py

Fixing crash on MacOSX filechooser

---

plyer/platforms/android/filechooser.py

#611 add filters for file chooser on android

---

plyer/platforms/android/filechooser.py
plyer/platforms/linux/wifi.py
plyer/platforms/win/screenshot.py

This PR fixes all the existing pep8 errors in this project.
Due to these errors, builds for most of the branch are failing.

Fixed pep8 errors

---

README.md

Support added in this PR https://github.com/kivy/plyer/pull/542

Added tick in ios native file chooser row

---

plyer/facades/keystore.py
plyer/facades/notification.py
plyer/platforms/linux/notification.py
plyer/platforms/linux/storagepath.py
plyer/platforms/win/filechooser.py

Fixes style issues introduced in #639 and #688

Fixes style check

---

plyer/facades/audio.py

Add missing platforms in audio docstring

Add missing platforms in audio

---

plyer/facades/filechooser.py

Updated filechooser.py docstring with supported platforms.

Document supported platforms in native filechooser

---

README.md
plyer/facades/orientation.py

Document linux support for orientation

---

plyer/__init__.py

- Bumps version to `2.1.0` for release

Bump version to 2.1.0 for release

---

CHANGELOG.md

- Adds CHANGELOG for release `1.3.1`
- Adds CHANGELOG for release `1.3.2`
- Adds CHANGELOG for release `1.4.0`
- Adds CHANGELOG for release `1.4.1`
- Adds CHANGELOG for release `1.4.2`
- Adds CHANGELOG for release `1.4.3`
- Adds CHANGELOG for release `2.0.0`
- Adds CHANGELOG for (upcoming) release `2.1.0`

Update CHANGELOG.md for release 2.1.0

---

CHANGELOG.md

- Include a last-minute PR in release 2.1.0

Update CHANGELOG.md for release 2.1.0 (part 2)

---

plyer/__init__.py

- Bump the development version to `2.2.0.dev0`

Bump to 2.2.0.dev0 for development

---

examples/maps/main.py

Add Maps example

---

plyer/platforms/android/gps.py

For reference: [LocationListener](https://developer.android.com/reference/android/location/LocationListener#onLocationChanged(java.util.List%3Candroid.location.Location%3E))
Is there another way you'd handle this List/make use of the OnLocationChanged?

Address LocationListener java method added with API31

---

README.md

Made a typo in #712 that nobody (including myself) caught.

Fix Supported Matrix typo

---

README.md
plyer/__init__.py
plyer/facades/maps.py
plyer/platforms/ios/maps.py

- Tested on iPhone SE (3rd Generation, iOS 15.5)

Add iOS implementation for Maps facade

---

plyer/platforms/linux/filechooser.py

Options are still supported, Just need to be used in different order.

Zenity options title, icon still supported.
