plyer/platforms/android/gps.py
Issue was first brought to light here: https://github.com/kivy/plyer/issues/54
GPS module was cycling through "gps" three times instead of all location services.
=> Android gps.py: fixed location provider cycling

plyer/platforms/ios/gps.py
Added support for GPS in iOS. Fixes issue #22
Working example: (on iPhone 5 and iOS 8)
=> iOS GPS support

plyer/platforms/linux/battery.py, plyer/platforms/macosx/battery.py, plyer/platforms/macosx/uniqueid.py
Using the protocol described in https://github.com/kivy/plyer/pull/115 to call external shell processes. This is to prevent issues due to localized output.
=> Use environ to change LANG to 'C' while calling shell processes

README.rst, plyer/__init__.py, plyer/facades.py, plyer/platforms/linux/filechooser.py, plyer/platforms/macosx/filechooser.py, plyer/platforms/win/filechooser.py
I renamed the branch to avoid confusion with qua-non's branch (native_dialogs) and reopened this pull request. It should be up to date with master now.
Needs testing for Windows.
The Mac OS X implementation will be ported soon.
=> Add file chooser facade and support for Linux and Windows

plyer/facades/uniqueid.py, plyer/platforms/android/uniqueid.py
Using Android_ID. 
Do I need to add something else?
=> fix #107 - Use Android_ID instead of IMEI

plyer/platforms/macosx/filechooser.py
The method is `runModal`, not `runModal:`.
=> macosx: fix incorrect method name in filechooser

plyer/platforms/ios/camera.py, plyer/utils.py
Depends upon Photolibrary on iOS https://github.com/kivy/kivy-ios/pull/154
=> Introduce camera access for ios and a example.

README.rst, examples/call/main.py, plyer/platforms/ios/call.py
Some days ago a user on IRC was asking about calling feature for ios, Here it is.
I have not tested it yet, maybe I will do it in a couple of days.
=> Call for ios

README.rst, plyer/platforms/ios/sms.py
=> add sms for ios

README.rst, examples/wifi/main.py, plyer/__init__.py, plyer/facades/__init__.py, plyer/facades/wifi.py, plyer/platforms/linux/wifi.py, plyer/platforms/macosx/wifi.py, plyer/platforms/win/libs/wifi_defs.py, plyer/platforms/win/wifi.py
This PR provides following features:
- Get the available device's name and network information.
- Scanning for available devices.
- Connect to network.
- Disconnect from network.
=> Wifi Facade. OSX, Windows, Linux

plyer/facades/gps.py
Adding note for iOS-specific steps required to use GPS.
This is my first PR attempt, so please reply on any issues with it so I could learn and improve!
This note is based on comments in platform/ios/gps.py and practical tests with iphone 6s / Xcode 7.2.1
Also it could be related to https://github.com/kivy/plyer/issues/173 - in my case missing key lead to configure() passing without issues but on_location() never getting called. Thus location was never updated.
Regrettably I was unable to test it on simulators for iphones newer than iphone 5 (4s and 5 run GPS with lcation simulation just fine)
=> Note on requirements for iOS

plyer/platforms/macosx/uniqueid.py
In macosx.uniqueid, `$LANG` is retrieved with `old_lang = environ.get('LANG')`. This means that if `LANG` is not set, `old_lang` will be none. When plyer later tries to restore the original value of lang, `putenv` will complain that we're not supplying a string.  I've corrected this by popping the inserted `LANG` value if `old_lang` is none.
=> Fix TypeError if `LANG` is not set in on osx

examples/camera/basic/README, examples/camera/basic/buildozer.spec, examples/camera/basic/camerademo.kv, examples/camera/basic/main.py
This is the basic example for the camera facade. Saves the image with the name given by the user.
=> Camera example

.gitignore
when we package our app using buildozer then bin and .buildozer directories are created which should not be committed.
=> add bin and .buildozer directory to .gitignore

README.rst, plyer/__init__.py
`IR Blaster` is implemented for the android platform but was not mentioned in README.rst
`__all__` in `plyer/__init__.py` contains all the supported features but `flash` was missing from there though its `proxy` is created.
There were not any issues happening without these changes but the information should be updated.
=> Update readme and plyer/__init__.py

README.rst, examples/light/buildozer.spec, examples/light/main.py, plyer/__init__.py, plyer/facades/__init__.py, plyer/facades/light.py, plyer/platforms/android/light.py
Android light sensor api to measure the ambient light level(illumination) in lx.
Can be merged.
Tested on:
Device - Xiaomi Mi 4i
Toolchain - old and new both
Android sdk - 24
Android api - 19
=> Android light sensor

plyer/facades/temperature.py
fixes pep8 error in temperature facade. Should be merged because the error prevents plyer to install in system.
=> Pep8 fix in temperature.py

examples/camera/basic/main.py, plyer/compat.py, plyer/facades/wifi.py, plyer/platforms/win/libs/wifi_defs.py
Tried wifi module on py3+win7, some obvious bugs fixed.
=> Fix wifi module.

plyer/platforms/linux/notification.py
- the API expects a value in seconds (but the DBus API uses milliseconds)
- the documentation says the default timeout is 10 seconds (not 5)
=> fix handling of notifications' timeout on Linux

plyer/platforms/win/libs/balloontip.py
`icon_path_name` is not defined. So passing an invalid icon file will raise an error about that instead of the expected Exception:
```
Traceback (most recent call last):
File ".\win-popup.py", line 6, in <module>
app_name='sync-seedbox', timeout=10)
File "C:\Tools\Python35\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 145, in balloon_tip
WindowsBalloonTip(**kwargs)
File "C:\Tools\Python35\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 91, in __init__
format(icon_path_name))
NameError: name 'icon_path_name' is not defined
```
=> Fix bug in WindowsBalloonTip

plyer/platforms/linux/notification.py
It does the same thing, except you can silence it if you wish. Given that you may very well not want to ever use the db-bus binding, it's nice to have the choice of sticking to notify-send without any mention of it in stder if you feel like it.
=> Warn instead stder.write for linux notif errors

README.rst, plyer/__init__.py, plyer/facades/__init__.py, plyer/facades/processors.py, plyer/platforms/linux/processors.py
Returns the Number Of Processors in Linux Platform. :computer:
=> Number Of Processors for Linux Platform

.travis.yml, plyer/tests/common.py, plyer/tests/test_facade.py
The previous approach used dynamically created files and imported each `Dummy` class from separate platform. That didn't work for OSX + Py3 and apparently had problems even on GNU/Linux + Py3 sometimes. Somehow it seems to me qua-non's idea about relative imports had something to do with it because I called `reload()` in the test.
I switched to dynamically created modules and mocked `__import__` instead, which seems to work + simplified the tests for each platform into a single one.
=> Fix test_facade failing for Py3 by switching to Mocks

plyer/platforms/macosx/battery.py
Switching to unicode as described in https://github.com/kivy/plyer/commit/3892b41a8d9a8006754d95c4dfc2903f12d16bf0#r29926437.
=> Switch to unicode in macosx battery.py

.travis.yml
because anything using a branch name wont work correctly with HEAD or hash.
=> Fix travis to use real branch instead of detached HEAD

plyer/platforms/android/notification.py
This is based on on @linuxrootok https://github.com/kivy/plyer/issues/154#issuecomment-412349523 and [Background-Service-using-P4A-android.service](https://github.com/kivy/kivy/wiki/Background-Service-using-P4A-android.service).
It was tested on Android 7 device, see [buildozer.spec](https://github.com/AndreMiras/EtherollApp/blob/v20180918/buildozer.spec) file for more details about the setup.
=> Clickable notifications, fixes #154

plyer/compat.py, plyer/utils.py, setup.py
Some errors are ignored due to py2/py3 compat and basically everything depending on some specific name + it makes no sense to make e.g. `XRANGE` (all upcase) for built-ins.
Also, I added the original author of `Proxy()` and its license (it's PSF, but just to be safe) to the docstring.
=> Fix style issues in utils, compat and setup.py

.travis.yml
The Docker image is still using Ubuntu Bionic inside
=> Downgrade Travis due to missing docker service on Ubuntu Bionic

plyer/platforms/macosx/storagepath.py
Changed OSX storage path implementation from using ctypes to pyobjus because of ctypes returning malformed path strings (probably null characters).
The implementation with the same Apple's Objective-C API as the one for iOS, OSX version works.
Related to issue #282 and pull request #428.
=> Changed OSX storage path from ctypes to pyobjus

plyer/platforms/win/filechooser.py
Fixes `"b'C:\\whatever'"` path, but doesn't break it with converting it to unicode, since the rest of the methods still use bytes on Py2 and unicode on Py3.
=> Fix b' embedded in the path string for Windows' choose_dir()

plyer/platforms/linux/orientation.py
Otherwise it fails on Py3 with expecting bytes in `split()`.
=> Fix not decoding bytes in Linux orientation.py

plyer/tests/test_screenshot.py
Py3 on MacOS currently fails due to PyOBJus missing Py3 support, otherwise it works fine.
=> Add screenshot test for OSX

README.rst, plyer/platforms/win/screenshot.py
Default format for Windows is a bitmap. Also this takes care of DPI if on versions that use it. If the DPI awareness isn't set e.g. on Win 8.1, the screenshot of 1080p is around ~1530p. In case user wants to set own awareness (per monitor or what not), we should always return it to the original state.
=> Add Windows Screenshot with ctypes+pywin32

plyer/platforms/android/battery.py
Looks like it has been broken by Auto replace of all "Intent" -> "INTENT" on Jul 10: https://github.com/kivy/plyer/commit/7ececb608dafb7663828d6cad6f45136e7c9fced#diff-8b8d9bc9ae852189c327adcd5e1f26ce
=> Fixing Java class name

.travis.yml, Dockerfile.archlinux.py2, Dockerfile.archlinux.py3, Dockerfile.fedora28.py2, Dockerfile.fedora28.py3, entrypoint.sh
Add more GNU/Linux distros, so that we can test if a feature x, y, z works on the most common distros (or their bases) such as Arch for Arch, Manjaro, others and Fedora for RedHat distros. We already have Ubuntu (therefore Mint and perhaps even Debian) covered.
I'm using Fedora 28 due to yum/dnf bug which is rather old one.
Only one distro will be used for deployment and that's the one with the style tests, unit tests and even coveralls' coverage report (`COVERALLS=1`).
=> Add more distros via Docker images

setup.py
More comfortable than using `try`/`except` and shut the user down with a warning. Instead we should provide an interface to install the conditional requirement, i.e. in this case `pyjnius` for Android platform and `pyobjus` for macOS/iOS.
Choosing non-intrusive installation option because it might break stuff for mobile platforms if enforcing the requirements on pyobjus/pyjnius + there are no releases of pyobjus/pyjnius yet (wip), therefore:
pip install plyer[macosx]
will for now just crash. The `dev` option will work though.
=> Add extra options for installation via setuptools

plyer/platforms/linux/uniqueid.py
`putenv()` fails if `None` is used which is the default if you want to get a value from a dictionary by a key. Also, another unnecessary `grep` purged along the way.
=> Fix uniqueid for linux platform

README.rst, plyer/__init__.py, plyer/facades/__init__.py, plyer/facades/cpu.py, plyer/platforms/linux/cpu.py, plyer/platforms/macosx/cpu.py, plyer/platforms/win/cpu.py, plyer/tests/common.py, plyer/tests/test_cpu.py
This one gives actually an explanation what the returned value means + separates the values into properties/methods:
* sockets (couldn't find for OSX yet, let's assume 1 slot for now)
* physical
* logical
* cache (Win + Lin for now)
* numa (Win only for now)
Some tests are still WIP because of mocking objects from ctypes and/or finding an official command/value such as `%NUMBER_OF_PROCESSORS%`.
Deprecating `processors` if anyone used it.
ref #419
=> New extended CPU details implementation

plyer/facades/wifi.py, plyer/platforms/linux/wifi.py
Previously we used `wlan0` which is not guaranteed to be even available on multiple distros/kernel versions, therefore using `wlan0` would fail with not available interface for any command. For example I have interface on one of my machines `wlpXsY`, therefore if anything, it'll fail with a different error.
The default behavior is to use the first listed interface retrieved by `nmcli` in case someone wants to create multiple interfaces / has more than one WiFi card (that's the main reason for `interface=None` optional kwargs). I have only one card and one interface though, therefore I haven't figured out how to retrieve a "primary" wifi interface. If anyone finds out, feel free to let me know or open an issue/PR.
WiFi connecting, disconnecting and anything with `import wifi` lines in it …
=> Add support for interfaces in Linux WiFi

README.rst, plyer/platforms/win/audio.py, plyer/tests/test_audio.py
Highly similar approach to #428, therefore even the test is almost identical (but won't run on Appveyor :cry: ). For now it uses the default format mentioned in Windows' documentation (`WAV`) so it's the same one as for macOS. I haven't found a way to specify sample rate and likes though.
=> Add audio recording and playing for Windows

.travis.yml, ci/osx_fix_rvm.sh
RVM causing problems on Travis again, this time it's fixed by removing `rvm get head` fix for an old-ish Travis issue. :disappointed:
=> Fix OSX builds on Travis

README.rst, examples/filechooser/main.py, plyer/facades/filechooser.py, plyer/facades/storagepath.py, plyer/platforms/android/filechooser.py, plyer/platforms/android/storagepath.py, plyer/platforms/linux/filechooser.py, plyer/platforms/macosx/filechooser.py, plyer/platforms/win/filechooser.py
Adds external (micro) SD card path detection because otherwise the filechooser would return wrong path e.g.:
/storage/emulated/0/file.txt
/storage/extSdCard/file.txt
Android lacks an official API for fetching the path to the external SD card, however `/storage` folder contains both internal and external card. A user can read only those files by default. *Might* be an issue for rooted devices though if the folders are available for reading for root. This should not be an issue due to file ownership of a `system` user, however manufacturers can change anything.
Due to the Android's internals we need to "listen" for the response from user's filechooser `Activity`. Implementation details are properly described in the platform filechooser file. The same listener approach is added even to the …
=> Add Android Native filechooser and external SD card path to StoragePath

examples/notification/main.py, examples/notification/notificationdemo.kv, plyer/facades/notification.py, plyer/platforms/android/notification.py
On Android there's the `Toast` message which we used(?, I've never seen it on any device) in p4a when the lib loading fails. This is another case of a notification for the used, kind of like very simple `print(message)`, so it might be a good thing to add.
The displaying of the icons was not implemented properly (`setLargeIcon()` missing) and I've seen it previously in one of the implementations either on old IRC or somewhere with Android service examples, but couldn't find any file with that. So it'd be only good to allow a user to set own big icon while preserving a small icon of the source application.
Ref https://developer.android.com/guide/topics/ui/notifiers/notifications#Templates.
=> Enhance Android notifications with toast and big icons

plyer/platforms/linux/wifi.py
Old `LinuxWifi` is marked as deprecated and will be removed after the next release. The current implementation fully relies on `nmcli` which is available on most popular distros. The next step is to add more low-level implementation that is purely based on kernel related stuff directly instead and `nmcli` as an alternative.
Closes #487.
=> Implement WiFi for Linux with nmcli

plyer/platforms/android/tts.py
The current version of plyer/platforms/android/tts.py crashes when calling tts.speak(). This issue can be replicated using the text2speach example provided in plyer's examples folder. That throws out error like the below line:
`
07-28 13:01:49.767 32640 32676 I python  :  jnius.jnius.JavaException: No methods matching your arguments, available: ['(Ljava/lang/CharSequence;ILandroid/os/Bundle;Ljava/lang/String;)I', '(Ljava/lang/String;ILjava/util/HashMap;)I']
`
As the above error suggested, this commit updated adnroid/tts.py to pass message in string rather than in encoded bytes, as encoded bytes is not compatible with java.lang.String, which leads to crash of tts.speak(). According to my own tests, this fix works for both armeabi-v7a and arm64-v8a.
My environment:
- Ubuntu 18.04
- …
=> fix the issue that tts.speak() crashes on android

plyer/platforms/android/vibrator.py
Fixes #501 #509
In this PR I implemented a solution considering the deprecations applied since API 26 (check https://developer.android.com/reference/android/os/Vibrator). In order to make the vibration work again, I had to first use jnius.cast with "android.os.Vibrator" and VIBRATOR_SERVICE.
Since API 26, the VIbrationEffect class admits different types of vibrations, but I just implemented https://developer.android.com/reference/android/os/VibrationEffect.html#createOneShot(long,%20int) and https://developer.android.com/reference/android/os/VibrationEffect.html#createWaveform(long[],%20int), otherwise I could break plyer's VIbrator API.
This PR has been already tested. Anyway, I invite you to try it and post the results.
=> Fix vibrator, which was not working on Android devices.

examples/gps/buildozer.spec, examples/gps/main.py
Not certain here if including the android dependency in the *requirements* line is correct? How does one include OS specific dependencies in a cross-platform library? Sho
=> Add permission request to plyer GPS example

plyer/platforms/linux/filechooser.py
Currently this crashes with:
```
File "/home/cheaterman/.local/lib/python3.7/site-packages/plyer/platforms/linux/filechooser.py", line 251, in _file_selection_dialog
desktop_override = desktop
NameError: name 'desktop' is not defined
```
when it should actually crash with:
```
File "/home/cheaterman/.local/lib/python3.7/site-packages/plyer/platforms/linux/filechooser.py", line 254, in _file_selection_dialog
raise OSError("No back-end available. Please install one.")
OSError: No back-end available. Please install one.
```
Thanks :-)
=> Handle absence of LinuxFileChooser backend

plyer/platforms/win/filechooser.py
This fixes a bunch of issues with filechooser on windows:
* When browsing for files and the user provides a initial default path, previously it'd set the default filename in the GUI to the final component of the provided path and the root to the dirname of the provided path. However, when passing a directory as the initial path, we should be using that path, not its parent, so that is fixed.
* The default extension included the period before the extension, but that made windows append two periods to the selected filename. So we strip the period before passing the extension to windows.
* The `OFN_EXTENSIONDIFFERENT` doesn't do anything because it's only set by windows, not by us, so I removed it.
* I added the `OFN_HIDEREADONLY` because before the GUI showed the option to open the file as …
=> Make win filechooser use modern windows browser and fix small issues.

plyer/platforms/win/storagepath.py, plyer/tests/test_storagepath.py
Added Windows applications storage path,
this will most likely point to C:\Program Files
Added Windows storage path tests.
Fixes issue #451
=> Add Windows applications storage path

plyer/platforms/android/filechooser.py
Closes #534
This issue can be easily verified by running this example.
https://github.com/kivy/plyer/tree/master/examples/filechooser
All is well when a file is selected, but pressing the back button to cancel selection crashes it (with the error log shown in #534) as the "getData()" method tries to fetch non-existent data.
=> Prevent crash when cancelling filechooser

plyer/platforms/android/notification.py
This pull request fixes the following error appearing in SDK_INT >= 26:
```
JNI DETECTED ERROR IN APPLICATION: bad arguments passed to
java.lang.Object android.app.Activity.getSystemService(java.lang.String)
```
It seems that the error is happening because there is a bug in pyjnius
where `getSystemService(java.lang.Class)` is not recognized. So, instead
of using `getSystemService(manager)`, `_get_notification_service` is
used, which returns `(NotificationManager)
getSystemService(Context.NOTIFICATION_SERVICE)`.
Fixes #504,  Fixes #533
=> Fix crash in Android Notification (SDK_INT >= 26)

plyer/facades/audio.py, plyer/platforms/macosx/audio.py
Fixes issue #515 and additionally fixes `TypeError: Can't mix strings and bytes in path components` with default audio `file_path` assignment.
Both fixes tested on Py2 and Py3.
=> Fix default audio file_path assignment error, file_path change for Py3

examples/gps/main.py
Warnings:
* F401 kivy.clock.Clock imported but unused.
* E303 too many blank lines.
=> Fix linter warnings in examples/gps/main.py

examples/accelerometer/using_graph/libs/garden/garden.graph/__init__.py, plyer/compat.py, plyer/platforms/win/libs/wifi_defs.py, plyer/tools/pep8checker/pep8.py
This is a follow up for https://github.com/kivy/plyer/pull/548
Note that we ignore the `plyer/tools/pep8checker/pep8.py` entirely as it
contains major issues such as `F821 undefined name`. I'd rather
completely delete this file and only rely on existing linting tools
rather using a custom one.
=> Fixes linter errors

plyer/platforms/macosx/filechooser.py
=> Fix uninitialized variable in MacOSX filechooser.

plyer/platforms/macosx/filechooser.py
I got the following issue from a user on Catalina:
From https://developer.apple.com/documentation/appkit/nssavepanel and https://developer.apple.com/documentation/appkit/nsopenpanel it seems we have been setting APIs that are only available in the open panel mode even for the save panel mode. This fixes it and move these calls to open mode only (open panel inherits from save panel).
=> Some APIs are only available for open panels.

plyer/platforms/linux/filechooser.py
Trinity Desktop Environment is a fork of KDE3 that does not set XDG_CURRENT_DESKTOP but does set DESKTOP_SESSION to `trinity`.
This pr added a check for that.
=> Add check for Trinity Desktop Environment

plyer/platforms/macosx/filechooser.py
This was failing with the following error
TypeError: '__NSArrayI' object is not iterable
=> FileChooser: MacOS: Use objectAtIndex_ to get multiple items

plyer/facades/accelerometer.py, plyer/facades/brightness.py, plyer/facades/sms.py, plyer/facades/wifi.py, plyer/platforms/ios/camera.py, plyer/platforms/ios/filechooser.py, plyer/platforms/ios/sms.py, plyer/platforms/ios/vibrator.py
There are small typos in:
- plyer/facades/accelerometer.py
- plyer/facades/brightness.py
- plyer/facades/sms.py
- plyer/facades/wifi.py
- plyer/platforms/ios/camera.py
- plyer/platforms/ios/filechooser.py
- plyer/platforms/ios/sms.py
- plyer/platforms/ios/vibrator.py
Fixes:
- Should read `specified` rather than `secified`.
- Should read `selection` rather than `seletion`.
- Should read `repetition` rather than `repeatition`.
- Should read `receiver` rather than `reveiver`.
- Should read `message` rather than `mesage`.
- Should read `chosen` rather than `choosen`.
- Should read `brightness` rather than `brightnesss`.
- Should read `accelerometer` rather than `acceletometer`.
Closes #622
=> docs: fix a few simple typos

README.md, plyer/__init__.py, plyer/facades/__init__.py, plyer/facades/devicename.py, plyer/platforms/android/devicename.py, plyer/platforms/linux/devicename.py, plyer/platforms/macosx/devicename.py, plyer/platforms/win/devicename.py, plyer/tests/test_devicename.py
This support is for adding a new feature (`plyer.devicename`) which will allow user to get the device name in case of an android  device.
This is also supported for linux and windows where it will return the hostname of the environment.
I also wanted to added support for ios ; but I don't have environment to test those.
Please review this PR.
PS: testing screenshot attached for windows and linux
Validated the functionality of socket.gethostname in MacOSX and added its support as well.
=> Support to get android device name or hostname for linux and windows

setup.py
Fixes #608 
Removed reference of Python 2.6 and 2.7 in setup.py file
Also added reference for Python 3.6, 3.7 and 3.8 in setup.py file
=> Removed python2.6|7 reference and added reference for python 3.6|7|8 

plyer/platforms/android/camera.py
As far as I know `org.renpy.android.PythonActivity` depracted, preferably and correctly used `org.kivy.android.PythonActivity`
=> Change `PythonActivity` java class

plyer/platforms/linux/filechooser.py
This PR resolves the issue that occurs on the KDE-based Linux distributions. 
The wrong flag was used. the right one is  
` --getsavefilename                 File dialog to save a file (arguments
[startDir] [filter])
`
=> fix: fix filechooser save dialog for the KDE

plyer/platforms/win/filechooser.py
Fixes Crash due to low buffer for selecting large number of files > 100
Ref: https://mail.python.org/pipermail/python-win32/2018-June/014071.html
=> Bigger buffer, allows large selection

plyer/platforms/macosx/filechooser.py
When clicking the close button, on OS X on_selection was not called
```py
from textwrap import dedent
from plyer import filechooser
from kivy.app import App
from kivy.lang import Builder
from kivy.properties import ListProperty
from kivy.uix.button import Button
class FileChoose(Button):
'''
Button that triggers 'filechooser.open_file()' and processes
the data response from filechooser Activity.
'''
selection = ListProperty([])
def choose(self):
'''
Call plyer filechooser API to run a filechooser Activity.
'''
filechooser.open_file(on_selection=self.handle_selection)
def handle_selection(self, selection):
'''
Callback function for handling the selection response from Activity.
'''
self.selection = selection
def on_selection(self, *a, **k):
'''
Update TextInput.text after …
```
=> Fix bug, when user canceled filechooser, `on_selection` does not dispatched

plyer/platforms/linux/filechooser.py
When clicking the close button, on *Linux* `on_selection` was not called. Same - #666 
```py
from textwrap import dedent
from plyer import filechooser
from kivy.app import App
from kivy.lang import Builder
from kivy.properties import ListProperty
from kivy.uix.button import Button
class FileChoose(Button):
'''
Button that triggers 'filechooser.open_file()' and processes
the data response from filechooser Activity.
'''
selection = ListProperty([], allownone=True)
def choose(self):
'''
Call plyer filechooser API to run a filechooser Activity.
'''
filechooser.open_file(on_selection=self.handle_selection)
def handle_selection(self, selection):
'''
Callback function for handling the selection response from Activity.
'''
self.selection = selection
def on_selection(self, *a, **k):
'''
Update …
```
=> Added the ability to track the closure of the file manager without selecting content

plyer/utils.py
Currently plyer uses the presence of the `ANDROID_ARGUMENT` environment variable to detect Android.  As of Python 3.7, there is a `sys.getandroidapilevel` that can be checked instead, which is more reliable since it does not require on a particular implementation detail of p4a.
=> Use sys.getandroidapilevel for more robust Android detection

plyer/platforms/android/filechooser.py
for android 11+ it is not possible to capture the real path of the files inside the documents folder, this implementation solves this scenario.
=> android 11+ compatibility Documents folder

plyer/platforms/linux/filechooser.py
The automated tests are currently failing due to pep8 violation. This PR fixes that pep8 error.
=> :hammer: Fix pep 8 failure for CICD

plyer/platforms/android/filechooser.py
Another trivial PR to fix CICD checks for PR's that fail on this Pep8 check
=> :zap: Fix pep8 violations

plyer/platforms/android/notification.py
Firstly, thank you so much for developing such a great library!  I'm excited to say that I've been having good success getting it to work with Panda3D applications.  There's one main obstacle that I can't overcome without changes to plyer, though.
Currently, the Notification implementation on Android makes the bold assumption that there is an R.class which has a field named "icon" that points to the icon resource of the application.  This need not be the case; the icon may not be named "icon" precisely, or there may not even be an R.class at all, since this is not actually required by Android, and it would be very painful to try and get Panda3D's packaging tool to compile an R.class file specifically for the sake of getting plyer to work.
So, this PR instead changes the mechanism to use …
=> More robust way to get application icon on Android for notification

plyer/platforms/linux/storagepath.py
The issues fixed are explained in the commits:
Author: Romanos Skiadas <rom.skiad@gmail.com>
Date:   Fri Sep 17 20:41:42 2021 +0300
linux/storagepath: Revamp handling of user-dirs
- dont assume that ~/.config/user-dirs.dirs exists
- don't assume it does have contents or the relevant value
- don't use exception handling as happy path control flow
- when defaulting, use the path under HOME, not e.g. /Pictures
commit 99dabb2d62248fc3ea5705c2720abf71c9fc378b
Author: Romanos Skiadas <rom.skiad@gmail.com>
Date:   Fri Sep 17 20:31:08 2021 +0300
linux/storagepath: Fixup DOCUMENTS to DOCUMENT
this is the right name according to the XDG spec, and the key used in
the default paths dict
This is a superset of https://github.com/kivy/plyer/pull/539. It both fixes more issues, and makes the code a bit …
=> linux/storagepath: fixup a host of issues

plyer/facades/notification.py, plyer/platforms/linux/notification.py
Hello!
Transient notifications (notifications that don't persist in the notifications list) are not programmable on Linux, even though they can be. The reason or this is because the `hint[s]` parameter required by `notify-send` and `dbus` cannot be passed to the base [`Notification.notify()`](https://github.com/kivy/plyer/blob/0c226e1fbc2f70d713654aa6443488d71b31af93/plyer/facades/notification.py#L48) method. 
I've implemented a simple solution that allows the other keyword arguments to be passed to the `notify()` method, allowing the underlying `_notify()` implementation to use `hint[s]` and other notification arguments as required.
Currently, trying to use hints with the `notify()` call fails: 
```
>>> from plyer import notification
>>> print(notification) …
```
=> Enabled transient notifications on Linux

README.md
Just an enhancement in the README.MD file.
This PR adds support to display badges of all the valuable contributors of this repo.
Here's how it looks ?
=> Added contributors in readme.md file

plyer/tests/test_notification.py
- `hints` is a `dict`, but during the test a `list` was expected.
=> Fixes a failing test for notification

plyer/facades/barometer.py
Fix docstring to include iOS in supported platforms
=> Add missing platform for barometer

setup.py
In accordance with pypa/twine#425, `license` keyword [should not](https://github.com/pypa/twine/issues/425#issuecomment-466436196) hold a multi-line file but rather simply be the name for the license. 
Could be potential fix for kivy/plyer#698 where raw Markdown is being displayed on PyPI. I am definitely interested in working for a fix for kivy/plyer#698 but would appreciate some guidance in where to start as I am more of a beginner.
=> Keyword should only hold name of license

examples/accelerometer/using_graph/main.py, examples/camera/basic/main.py, plyer/facades/humidity.py, plyer/platforms/android/accelerometer.py, plyer/platforms/android/camera.py, plyer/platforms/android/compass.py, plyer/platforms/android/gyroscope.py, plyer/platforms/ios/camera.py, plyer/platforms/ios/tts.py, plyer/platforms/macosx/libs/osx_motion_sensor.py
- A recent change in `pycodestyle` (See: https://github.com/PyCQA/pycodestyle/pull/1063) introduced this check.
- CI runs started to fail this recently.
=> Fixes some E275. + other minor PEP8 fixes

.github/workflows/plyer_deploy.yml
- Bumps `action-gh-release` to a newer version, in order to get ready for a new plyer release.
=> Bump action-gh-release to a newer version

.github/workflows/plyer_deploy.yml
`action-gh-release` now uses `github.token` (by default, so doesn't need any config)
=> action-gh-release now uses `github.token`

README.md, plyer/facades/sms.py, plyer/platforms/macosx/sms.py
Extending support for sending messages for macOS systems!
Couple things to note:
- The implementation is really meant for iMessages, as are natively supported by macOS. SMS will only work on macOS if a device that is carrier-activated is [correctly paired and configured](https://support.apple.com/guide/messages/get-sms-texts-from-iphone-on-your-mac-icht8a28bb9a/mac). If SMS is desired, simply passing it into `sms.send(mode='SMS')` will correctly switch the mode. 
- My implementation has been tested with the existing example, and does work on on `macOS Monterey 12.5`
=> SMS support for macOS!

plyer/platforms/android/filechooser.py
**This works like a charm!**
Tested on: _python 3.8.15; kivy 2.1.0;  plyer 2.1.0; Android 13 on pure AOSP_
**Pros:**
**Cons:**
Still uses deprecated onActivityResult (same as `open_file` does. I think this is not so bad (This also used on the Google's guide).
Improvements and tests are appreciated!
Closes #661  ;)
=> feat(android-filechooser): Implement save file method

plyer/platforms/linux/filechooser.py
YAD removed support for its --file-selection option, which was an alias for --file, in commit 50c964d742 on Aug 4, 2019 (that commit removed all ...-selection aliases).
This change passes --file instead, which is present in all versions of YAD on GitHub to date.
I tested this by running it under WSL2 with YAD installed (all in a conda environment) and observing that the resulting YAD dialog now shows the file chooser dialog.
closes #744
=> YADFileChooser: s/--file-selection/--file/

.github/workflows/ci_ubuntu.yml
This led to the coverage never being uploaded for this job
=> :pencil2: Fix github.ref typo on coverage upload

plyer/platforms/android/notification.py
fixes https://github.com/kivy/plyer/issues/702
see https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
> Pending intents mutability
>   If your app targets Android 12, you must specify the mutability of
>   each PendingIntent object that your app creates. This additional
>   requirement improves your app's security.
see https://stackoverflow.com/q/69088578
Without this, I get the following exception: `JavaException('JVM exception occurred: org.electrum.testnet.electrum: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.\nStrongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to …
=> android: fix notification.notify() for sdk>=31, by setting new req flag

plyer/platforms/android/filechooser.py
When selecting a file in the `Documents` option in the navigation panel, the `uri_authority` returned is `'com.android.providers.media.documents'`. However the selection will fail because the `_handle_media_documents` method only handles `audio`, `video` or `image` and ignores any other type of file. Finally, `None` will be returned as the file path.
`python-for-android` version: `2023.2.10`
`buildozer` version: `1.5.0`
**Android API levels:**
- `27`
- `28`
- `31`
=> Fixes error when selecting a file from the `Documents` option in newer Android APIs

plyer/platforms/android/filechooser.py, plyer/platforms/android/storagepath.py
When trying to access the memory card directory in the latest android APIs, an error occurs.
Newer API levels do not allow access to content within `/storage`, resulting in a permissions error.
`python-for-android` version: `2023.2.10`
`buildozer` version: `1.5.0`
**Android API levels:**
- `27`
- `28`
- `31`
=> Fixed issue accessing sd_card path in newer Android APIs

plyer/platforms/android/filechooser.py
This PR fixes the error when selecting a file from the sidebar `Downloads` option. In most cases the selection would fail with the following errors:
1. invalid URI:
jnius.jnius.JavaException: JVM exception occurred: Unknown URI: content://downloads/public_downloads/1034
2. missing URI / android permissions
jnius.jnius.JavaException: JVM exception occurred: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/1034 from pid=2532, uid=10455 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
**Note:** The previous code was kept, in case the first option fails.
`python-for-android` version: `2023.2.10`
`buildozer` version: `1.5.0`
**Android API levels:**
- `27`
- `28`
- `31`
=> Fixes error when selecting a file from the `Downloads` option in the navigation panel

.github/workflows/support.yml, CODE_OF_CONDUCT.md, CONTACT.md, CONTRIBUTING.md, FAQ.md, LICENSE, README.md, docs/source/api.rst, docs/source/conf.py, docs/source/contact.rst, docs/source/contribute.rst, docs/source/faq.rst, docs/source/index.rst, examples/accelerometer/using_graph/libs/garden/garden.graph/__init__.py, examples/compass/main.py, examples/gyroscope/main.py, setup.py
This is part of an effort to make the Kivy sibling projects' documentation
structure consistent and up-to-date.
Unrelated changes:
* Readme Copy-edit. Reformat markdown table
* RST added structure, including API page
* Congrats, promoted from "beta" to "stable".
* Fixed some (but not all) unrelated PEP8 changes
CHECKLIST
* CONTRIBUTING.md
[x] If repo takes user contributions, is present
[x] In root dir (not .github dir)
[x] Refers to kivy/kivy Contribution Guidelines.
* LICENSE
[x] If repo takes user contributions, is present.
[x] Acknowledges the range of years to 2023.
[x] Acknowledges Kivy Team and other contributors
[x] Mentions it is an MIT License.
* CODE_OF_CONDUCT.md
[x] If repo takes user contributions or hosts discussions, is present.
[x] Refers to kivy/kivy CODE_OF_CONDUCT.md
* …
=> Make doc structure consistent and up-to-date   

docs/source/conf.py, plyer/platforms/android/filechooser.py, plyer/platforms/linux/filechooser.py, plyer/platforms/macosx/filechooser.py, plyer/platforms/win/filechooser.py
The style checks are currently failing (https://github.com/kivy/plyer/actions/runs/7139373418/job/19442606575) and this PR aims to fix all the issues found via flake8
=> Fix pep8 failures, and apply black formatting where applicable.

devrequirements.txt, plyer/tests/test_battery.py, plyer/tests/test_cpu.py, plyer/tests/test_devicename.py, plyer/tests/test_email.py, plyer/tests/test_facade.py, plyer/tests/test_notification.py, plyer/tests/test_screenshot.py, plyer/tests/test_uniqueid.py, plyer/tests/test_utils.py, setup.py
mock is now part of the Python standard library, available as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards.
https://github.com/testing-cabal/mock
=> replace old mock by unittest.mock

plyer/platforms/linux/filechooser.py
Resolves #821 
* --file-selection is now obsolete
* --name option in zenity file chooser was abruptly dropped starting in Ubuntu 24 (which prompted this PR)
* --window-icon option was dropped (unknown when, but would also cause it to fail)
```
/usr/bin/zenity --help-file-selection
Usage:
zenity [OPTION…]
File selection options
--file-selection                                  Display file selection dialog
--filename=FILENAME                               Set the filename
--multiple                                        Allow multiple files to be selected
--directory                                       Activate directory-only selection
--save                                            Activate save mode
--separator=SEPARATOR                             Set output separator character …
```
=> remove unsupported options for Zenity

plyer/platforms/linux/filechooser.py
[`distutils` is not included in newer python versions](https://docs.python.org/3.11/whatsnew/3.10.html#distutils-deprecated), in python `3.12` it throws `ImportError`, so it is good to migrate to `shutil`
> The entire distutils package is deprecated, to be removed in Python 3.12. Its functionality for specifying package builds has already been completely replaced by third-party packages setuptools and packaging, and most other commonly used APIs are available elsewhere in the standard library (such as [platform](https://docs.python.org/3.11/library/platform.html#module-platform), [shutil](https://docs.python.org/3.11/library/shutil.html#module-shutil), [subprocess](https://docs.python.org/3.11/library/subprocess.html#module-subprocess) or …
=> Migrate from `distutils` to `shutil` for finding executables

plyer/platforms/win/filechooser.py
Set value for the "DefExt" key so that Windows will append the extension to the returned file name.
=> Set "DefExt" argument in Win32FileChooser run method.

plyer/platforms/win/filechooser.py
This changes the Win32FileChooser to apply `os.path.normpath` to the path parameter before passing it on to pywin32. This allows the filechooser's path parameter to work properly without the end-user having to normalize the path first.
=> Normalize path when passing args to windows filechooser

plyer/facades/storagepath.py, plyer/platforms/ios/storagepath.py, plyer/platforms/macosx/storagepath.py, plyer/tests/test_storagepath.py
This pull request introduces a new feature to return the macOS desktop path for use in the StoragePath module. This addition allows access to the user's desktop directory on macOS systems, improves cross-platform compatibility, and simplifies file operations related to the OSX.
Key changes:
Added a new function _get_desktop_dir() to retrieve the desktop path on macOS
Added the get_desktop_dir() to the StoragePath facade
Added a line in the test_storagepath.py to test whether it works as intented
Please review and let me know if any further modifications are needed.
=> Added feature to return macOS desktop path for StoragePath
